# Assignment10

## Name: YangMyungCheol (양명철)
## ID: 20122776
## Submission Time: 2019.06.05. 15:15

Let x = $(x_1, x_2, ... , x_m)$ be a vector representing an image in the dataset.

The prediction function $f_d(x; w)$ is defined by the linear combination of data (1, x) and the model parameter w for each digit d :
$f_d(x; w) = w_0 * 1 + w_1 * x_1 + w_2 * x_2 + ... + w_m * x_m $
where w = $(w_0, w_1, ... , w_m)$

The prediction function $f_d(x; w)$ should have the following values:
$f_d(x; w) = +1$ if label(x) = d 
$f_d(x; w) = -1$ if label(x) is not d 

The optimal model parameter w is obtained by minimizing the following objective function for each digit d :
$\sum_i$ $( f_d(x^(i); w) - y^(i) )^2$

and the label of input x is given by:

$argmax_d f_d(x; w)$

1. Compute an optimal model parameter using the training dataset for each classifier $f_d(x, w)$
2. Compute (1) true positive rate, (2) error rate using (1) training dataset and (2) testing dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as lin
import copy 
import random
from sklearn.metrics import confusion_matrix

# train set

In [2]:
tr = pd.read_csv("mnist_train.csv", header=-1)

In [3]:
tr_data = np.array(tr)

In [4]:
tr_y, tr_x = np.split(tr_data, [1], axis=1)
tr_y_bin = copy.copy(tr_y)

In [5]:
number= 60000
tr_x_short = tr_x[:number]
yy = tr_y_bin[:number]

In [6]:
def min_max(data):
    result = (data-data.min()) / (data.max() - data.min())
    return result

In [7]:
tr_x_scale = min_max(tr_x_short)

In [8]:
one = np.ones((tr_x_scale.shape[0], 1))

In [9]:
A = np.concatenate((one,tr_x_scale),axis = 1)

In [10]:
print(A.shape)
A = A.reshape(1, len(A) * len(A[0]))
print(A.shape)

(60000, 785)
(1, 47100000)


In [11]:
for i in range(len(A[0])):
    A[0][i] = float(A[0][i]) + random.random()*0.0000001

In [12]:
A = A.reshape(60000, 785)

In [13]:
def classifier(digit):
    
    for i in range(tr_y_bin.shape[0]):
        if tr_y[i][0] == digit:
            tr_y_bin[i][0] =  1
        else:
            tr_y_bin[i][0] = -1

        
    yy = tr_y_bin[:number] 

    Beta = np.dot(np.dot(lin.inv(np.dot(A.T, A)), A.T), yy)

    return Beta

    

In [14]:
Beta0 = classifier(0)
Beta1 = classifier(1)
Beta2 = classifier(2)
Beta3 = classifier(3)
Beta4 = classifier(4)
Beta5 = classifier(5)
Beta6 = classifier(6)
Beta7 = classifier(7)
Beta8 = classifier(8)
Beta9 = classifier(9)

1. Compute an optimal model parameter using the training dataset for each classifier $f_d(x, w)$


In [15]:
# optimal model parameter for 0~9
print(Beta0)
print(Beta1)
print(Beta2)
print(Beta3)
print(Beta4)
print(Beta5)
print(Beta6)
print(Beta7)
print(Beta8)
print(Beta9)

[[-6.84674823e-01]
 [-1.52380549e+04]
 [ 8.58853665e+04]
 [ 8.92785688e+04]
 [ 4.39076191e+04]
 [ 1.12434754e+04]
 [-2.15372077e+04]
 [ 1.91109481e+04]
 [-1.18875197e+05]
 [ 6.84764988e+04]
 [ 3.04656722e+04]
 [-3.00027193e+04]
 [-1.39615711e+04]
 [ 3.37720318e+04]
 [-1.54231604e+04]
 [ 1.52498236e+04]
 [-3.33632985e+04]
 [-8.09187898e+04]
 [-2.49780101e+04]
 [ 1.38357352e+04]
 [-1.35219549e+03]
 [-2.98300406e+03]
 [ 4.15276756e+04]
 [ 1.55865878e+04]
 [-9.46072660e+04]
 [ 6.92038684e+04]
 [ 6.11450182e+04]
 [ 1.65519186e+04]
 [ 2.18032460e+04]
 [ 5.22562340e+04]
 [ 5.60386397e+04]
 [ 2.26684577e+04]
 [-1.27945745e+05]
 [-1.00442347e+01]
 [ 3.02809496e+00]
 [ 6.97786556e-02]
 [ 2.17474271e-01]
 [ 6.56241697e-02]
 [ 1.34518093e-02]
 [ 4.78092713e-02]
 [ 1.21322411e-01]
 [-7.48110960e-02]
 [ 2.74454183e-01]
 [-1.73342259e-01]
 [ 7.30952010e-02]
 [-4.55309112e-03]
 [ 7.98121257e-02]
 [-6.86309499e-02]
 [ 3.23164669e-02]
 [ 7.44470193e-02]
 [-1.32458011e-01]
 [ 2.28405714e-01]
 [ 1.4972494

 [ 2.62206868e+04]]
[[-7.04653742e-01]
 [ 8.71291778e+03]
 [-6.77141930e+04]
 [-2.55216170e+04]
 [ 9.47421940e+04]
 [ 1.01886319e+04]
 [ 5.07711847e+04]
 [-5.50331617e+03]
 [-6.81351090e+03]
 [-3.66789064e+04]
 [-7.42220250e+04]
 [-7.83500943e+03]
 [-9.84271898e+02]
 [-8.69372584e+04]
 [ 3.97037455e+04]
 [-3.82643213e+04]
 [ 6.20469869e+04]
 [ 1.81401493e+04]
 [-1.55693643e+04]
 [-1.56140346e+04]
 [ 3.10490400e+04]
 [ 4.98811075e+04]
 [-4.50845242e+04]
 [ 2.50789560e+04]
 [ 1.82609702e+03]
 [ 2.16608339e+04]
 [ 2.03633938e+05]
 [ 5.57058678e+03]
 [-7.81512644e+04]
 [-2.78863186e+04]
 [-7.61251950e+04]
 [ 1.29573591e+04]
 [-5.25503739e+04]
 [ 9.80251840e+00]
 [-3.32831990e+00]
 [-3.20876148e-01]
 [-5.12449462e-02]
 [ 7.17663821e-02]
 [-7.06172757e-02]
 [ 6.92844976e-02]
 [-2.00813967e-02]
 [-1.55530359e-01]
 [ 1.33114054e-01]
 [-1.14273151e-01]
 [ 3.05930710e-02]
 [-1.12134284e-01]
 [-2.07597214e-02]
 [ 7.82193902e-02]
 [-1.03114630e-01]
 [ 1.45049938e-01]
 [ 1.77523542e-02]
 [ 2.466609

In [16]:
pr0 = np.dot(A, Beta0)
pr1 = np.dot(A, Beta1)
pr2 = np.dot(A, Beta2)
pr3 = np.dot(A, Beta3)
pr4 = np.dot(A, Beta4)
pr5 = np.dot(A, Beta5)
pr6 = np.dot(A, Beta6)
pr7 = np.dot(A, Beta7)
pr8 = np.dot(A, Beta8)
pr9 = np.dot(A, Beta9)

In [18]:
arg = np.column_stack((pr0, pr1, pr2, pr3, pr4, pr5, pr6, pr7, pr8, pr9))

In [19]:
max_index_list =[]
for i in range(A.shape[0]):
    max_index_list.append(np.argmax(arg[i]))

In [20]:
np.unique(max_index_list)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [21]:
max_index_list

[5,
 0,
 4,
 1,
 9,
 2,
 1,
 3,
 1,
 4,
 3,
 5,
 3,
 6,
 1,
 7,
 2,
 8,
 6,
 7,
 4,
 0,
 9,
 1,
 2,
 2,
 4,
 3,
 7,
 1,
 3,
 8,
 6,
 7,
 0,
 5,
 6,
 0,
 4,
 6,
 1,
 8,
 7,
 9,
 3,
 9,
 8,
 5,
 5,
 3,
 3,
 0,
 7,
 7,
 7,
 8,
 0,
 9,
 4,
 1,
 4,
 4,
 6,
 0,
 4,
 5,
 6,
 1,
 0,
 0,
 1,
 7,
 1,
 6,
 3,
 0,
 2,
 1,
 1,
 7,
 0,
 0,
 2,
 6,
 7,
 8,
 3,
 9,
 0,
 4,
 6,
 7,
 4,
 6,
 8,
 0,
 7,
 8,
 3,
 1,
 9,
 9,
 1,
 7,
 1,
 1,
 6,
 3,
 0,
 2,
 9,
 3,
 1,
 1,
 0,
 4,
 9,
 2,
 0,
 0,
 7,
 0,
 6,
 7,
 1,
 8,
 6,
 4,
 1,
 6,
 3,
 4,
 1,
 7,
 4,
 3,
 3,
 1,
 5,
 4,
 3,
 7,
 4,
 8,
 8,
 5,
 8,
 6,
 4,
 3,
 1,
 6,
 1,
 9,
 9,
 6,
 0,
 3,
 9,
 2,
 4,
 2,
 9,
 4,
 4,
 6,
 4,
 9,
 7,
 0,
 9,
 2,
 7,
 1,
 1,
 5,
 9,
 1,
 6,
 3,
 7,
 3,
 3,
 9,
 1,
 7,
 6,
 2,
 8,
 2,
 6,
 5,
 0,
 7,
 4,
 9,
 7,
 8,
 3,
 2,
 1,
 1,
 5,
 3,
 6,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 2,
 7,
 3,
 0,
 4,
 6,
 5,
 2,
 6,
 4,
 7,
 9,
 8,
 9,
 9,
 5,
 0,
 7,
 1,
 6,
 2,
 0,
 3,
 5,
 4,
 6,
 5,
 1,
 6,
 3,
 7,
 8,
 8,
 0,
 9,
 1,
 0,


In [22]:
acutal_y = tr_y.tolist()
data = {'y_Predicted': max_index_list,
        'y_Actual':    acutal_y
        }

df = pd.DataFrame(data, columns=['y_Actual','y_Predicted'])
#print (df)

      y_Actual  y_Predicted
0          [5]            5
1          [0]            0
2          [4]            4
3          [1]            1
4          [9]            9
5          [2]            2
6          [1]            1
7          [3]            3
8          [1]            1
9          [4]            4
10         [3]            3
11         [5]            5
12         [3]            3
13         [6]            6
14         [1]            1
15         [7]            7
16         [2]            2
17         [8]            8
18         [6]            6
19         [9]            7
20         [4]            4
21         [0]            0
22         [9]            9
23         [1]            1
24         [1]            2
25         [2]            2
26         [4]            4
27         [3]            3
28         [2]            7
29         [7]            1
...        ...          ...
59970      [2]            2
59971      [2]            2
59972      [0]            0
59973      [9]      

In [23]:
confusion_matrix_tr = confusion_matrix(acutal_y,max_index_list)

In [24]:
confusion_matrix_tr

array([[5685,    7,   18,   13,   23,   41,   64,    5,   61,    6],
       [   2, 6547,   39,   17,   20,   34,   13,   10,   54,    6],
       [  96,  264, 4796,  146,  109,   11,  233,   91,  193,   19],
       [  40,  170,  171, 5158,   33,  126,   56,  114,  136,  127],
       [   8,  100,   44,    7, 5209,   51,   42,   23,   57,  301],
       [ 158,   94,   27,  432,  107, 4000,  193,   37,  235,  138],
       [ 111,   74,   61,    2,   73,   88, 5471,    0,   34,    4],
       [  56,  190,   37,   46,  163,   10,    3, 5435,   10,  315],
       [  72,  488,   62,  229,  108,  216,   59,   20, 4422,  175],
       [  67,   57,   17,  118,  370,   12,    3,  487,   39, 4779]],
      dtype=int64)

In [25]:
TP_tr =0
r_sum = np.sum(confusion_matrix_tr, axis = 1)
print(r_sum)

for i in range(confusion_matrix_tr.shape[0]):
    TP_tr += confusion_matrix_tr[i][i] / r_sum[i]

TP_tr /= 10
TP_tr

[5923 6742 5958 6131 5842 5421 5918 6265 5851 5949]


0.8557761077392481

In [26]:
TP_tr

0.8557761077392481

In [27]:
Error_tr = 1- np.trace(confusion_matrix_tr)/ sum(sum(confusion_matrix_tr))

2. Compute (1) true positive rate, (2) error rate using (1) training dataset

In [28]:
print("train TP Rate : " + str(TP_tr))
print("train Error Rate : " + str(Error_tr))


train TP Rate : 0.8557761077392481
train Error Rate : 0.1416333333333334


# Test set

In [29]:
ts = pd.read_csv("mnist_test.csv", header=-1)

In [30]:
ts_data = np.array(ts)

In [31]:
ts_y, ts_x = np.split(ts_data, [1], axis=1)
ts_y_bin = copy.copy(ts_y)

In [32]:
number= 10000
ts_x_short = ts_x[:number]
yy_s = ts_y_bin[:number]

In [33]:
ts_x_scale = min_max(ts_x_short)

In [34]:
one_s = np.ones((ts_x_scale.shape[0], 1))

In [35]:
A_s = np.concatenate((one_s,ts_x_scale),axis = 1)

In [36]:
#print(A_s.shape)
A_s = A_s.reshape(1, len(A_s) * len(A_s[0]))
#print(A_s.shape)

(10000, 785)
(1, 7850000)


In [37]:
for i in range(len(A_s[0])):
    A_s[0][i] = float(A_s[0][i]) + random.random()*0.0000001

In [38]:
A_s = A_s.reshape(10000, 785)

In [39]:
np.unique(ts_y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [56]:
pr_s0 = np.dot(A_s, Beta0)
pr_s1 = np.dot(A_s, Beta1)
pr_s2 = np.dot(A_s, Beta2)
pr_s3 = np.dot(A_s, Beta3)
pr_s4 = np.dot(A_s, Beta4)
pr_s5 = np.dot(A_s, Beta5)
pr_s6 = np.dot(A_s, Beta6)
pr_s7 = np.dot(A_s, Beta7)
pr_s8 = np.dot(A_s, Beta8)
pr_s9 = np.dot(A_s, Beta9)

In [57]:
arg_s = np.column_stack((pr_s0, pr_s1, pr_s2, pr_s3, pr_s4, pr_s5, pr_s6, pr_s7, pr_s8, pr_s9))

In [58]:
max_index_list_s =[]
for i in range(A_s.shape[0]):
    max_index_list_s.append(np.argmax(arg_s[i]))

In [59]:
np.unique(max_index_list_s)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [60]:
acutal_y_s = ts_y.tolist()
data_s = {'y_Predicted': max_index_list_s,
        'y_Actual':    acutal_y_s
        }

df_s = pd.DataFrame(data_s, columns=['y_Actual','y_Predicted'])
#print (df_s)

     y_Actual  y_Predicted
0         [7]            7
1         [2]            2
2         [1]            1
3         [0]            0
4         [4]            4
5         [1]            1
6         [4]            4
7         [9]            9
8         [5]            5
9         [9]            9
10        [0]            0
11        [6]            4
12        [9]            9
13        [0]            0
14        [1]            1
15        [5]            5
16        [9]            9
17        [7]            7
18        [3]            3
19        [4]            4
20        [9]            9
21        [6]            6
22        [6]            6
23        [5]            5
24        [4]            4
25        [0]            0
26        [7]            7
27        [4]            4
28        [0]            0
29        [1]            1
...       ...          ...
9970      [5]            3
9971      [2]            2
9972      [4]            4
9973      [9]            9
9974      [4]            4
9

In [61]:
confusion_matrix_ts = confusion_matrix(acutal_y_s,max_index_list_s)

In [62]:
confusion_matrix_ts

array([[ 945,    0,    1,    2,    2,    9,   12,    2,    6,    1],
       [   0, 1107,    2,    2,    3,    1,    5,    1,   14,    0],
       [  19,   55,  810,   25,   15,    0,   42,   22,   38,    6],
       [   4,   19,   23,  881,    5,   16,    9,   20,   22,   11],
       [   0,   20,    6,    2,  882,    5,   10,    2,   11,   44],
       [  23,   18,    3,   73,   22,  659,   23,   13,   42,   16],
       [  18,   11,   10,    0,   23,   17,  873,    0,    6,    0],
       [   5,   42,   15,    5,   26,    0,    1,  884,    1,   49],
       [  14,   46,   11,   33,   26,   38,   15,   12,  759,   20],
       [  16,   11,    2,   17,   79,    1,    1,   77,    4,  801]],
      dtype=int64)

In [63]:
TP_ts =0
r_sum_s = np.sum(confusion_matrix_ts, axis = 1)
print(r_sum_s)

for i in range(confusion_matrix_ts.shape[0]):
    TP_ts += confusion_matrix_ts[i][i] / r_sum_s[i]

TP_ts /= 10
TP_ts

[ 980 1135 1032 1010  982  892  958 1028  974 1009]


0.8578045051177978

In [64]:
Error_ts = 1 - np.trace(confusion_matrix_ts)/ sum(sum(confusion_matrix_ts))

2. Compute (1) true positive rate, (2) error rate using (2) testing dataset.

In [65]:
print("test TP Rate : " + str(TP_ts))
print("test Error Rate : " + str(Error_ts))


test TP Rate : 0.8578045051177978
test Error Rate : 0.13990000000000002
